### ISSUE TITLE
Idea sounds great, Refar's name is poor

### ISSUE THREAD

**Issue by przeor** [FourSS/refar#1]
Hello Guys,

Just wanted to make you aware that your name is poor.

How to google refar related stuff in G without getting a lot of garbage?

https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=javascript+refar&nfpr=1

Regards,
Kamil ;-)

**Comment by a9a4k** [comment]
@przeor Did not think about that. It is still an infancy stage though, so if you have better suggestion we can change it ;)

**Comment by przeor** [comment]
let's keep in touch, ping me at kamil@przeorski.pl - maybe we can make a skype call :-) I am interested in that area that you are exploring :)

**Comment by przeor** [comment]
my email : kamil@przeorski.pl - ping me plz :-)  @almasakchabayev
